// [line 2] Error at 'foo': Expect '(' after 'fun'.
while (true) fun foo() {}
